### ISSUE TITLE
Port to npm mode

### ISSUE THREAD

**Issue by mvysny** [mvysny/karibu-helloworld-application#2]
Port the project to use Vaadin 14 + npm + webpack + Polymer 3 mode.

**Comment by mvysny** [comment]
Blocked by https://github.com/devsoap/gradle-vaadin-flow/issues/240

**Comment by johndevs** [comment]
Hi @mvysny, a beta version of the plugin should now be available for testing. 

There is still the issue of devsoap/gradle-vaadin-flow#285 which I hope to get solved soon, otherwise it should work (If you want to check it out and try to fix it there is a bounty on it available).

You should be getting your PRO license in your mail soonish so you can test it out ;)

**Comment by mvysny** [comment]
Hey @johndevs thanks a ton, I'll give it a go tomorrow :)

**Comment by mvysny** [comment]
Take use of the official Vaadin Gradle plugin when it's out, should be out soon-ish: https://vaadin.com/forum/thread/17830616/17918359

**Comment by mvysny** [comment]
Ported :+1:
